// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Geoprocessing/resultrenderers/FeatureSetRenderer.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"output-label" data-dojo-attach-point\x3d"labelNode"\x3e\r\n    \x3cspan\x3e${nls.drawnOnMap}\x3c/span\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"clear-node" data-dojo-attach-point\x3d"clearNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"export-node" data-dojo-attach-point\x3d"exportNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/dom-style dojo/on dijit/_TemplatedMixin esri/layers/GraphicsLayer esri/layers/FeatureLayer esri/graphicsUtils esri/renderers/SimpleRenderer esri/renderers/jsonUtils esri/InfoTemplate jimu/exportUtils jimu/dijit/ExportChooser dojo/text!./FeatureSetRenderer.html ../BaseResultRenderer ../LayerOrderUtil ./defaultSymbol".split(" "),function(m,e,n,p,c,f,q,r,s,t,h,u,v,l,w,x,y,z,k){return m([y,q],{baseClass:"jimu-gp-resultrenderer-base jimu-gp-renderer-draw-feature",
templateString:x,postCreate:function(){this.inherited(arguments);this.value.features&&0<this.value.features.length&&(this._displayText(),this._drawResultFeature(this.param,this.value))},destroy:function(){this.resultLayer&&this.map.removeLayer(this.resultLayer);this.inherited(arguments)},_displayText:function(){c.set(this.clearNode,"display","");this.own(f(this.clearNode,"click",e.hitch(this,function(){this.resultLayer&&(this.map.infoWindow.isShowing&&this.map.infoWindow.hide(),this.resultLayer.clear(),
this.map.removeLayer(this.resultLayer));c.set(this.exportNode,"display","none");c.set(this.labelNode,"display","none")})));if(this.config.showExportButton){c.set(this.exportNode,"display","");var a=l.createDataSource({type:l.TYPE_FEATURESET,data:this.value,filename:this.param.name});this.exportChooser=new w({dataSource:a});this.exportChooser.hide();p.place(this.exportChooser.domNode,this.domNode);this.own(f(this.exportNode,"click",e.hitch(this,function(a){a.preventDefault();a.stopPropagation();this.exportChooser.show(47,
28)})))}},_drawResultFeature:function(a,b){if(this.config.shareResults){if(!a.defaultValue||!a.defaultValue.geometryType)throw Error("Output parameter default value does not provide enough information to draw feature layer.");a.defaultValue.name=a.name;this.resultLayer=new s({layerDefinition:a.defaultValue,featureSet:null},{id:this.widgetUID+a.name})}else this.resultLayer=new r({id:this.widgetUID+a.name});this.resultLayer.title=a.label||a.name;this._addResultLayer(a.name);a.popup||(a.popup={enablePopup:!0,
title:"",fields:[]});var A=b.features.length,d=a.renderer;d?d=u.fromJson(d):"esriGeometryPoint"===b.geometryType?d=new h(k.pointSymbol):"esriGeometryPolyline"===b.geometryType?d=new h(k.lineSymbol):"esriGeometryPolygon"===b.geometryType&&(d=new h(k.polygonSymbol));var c;a.popup.enablePopup&&(c=new v(a.popup.title||"${Non-Exist-Field}",this._generatePopupContent(b)));for(var g=0;g<A;g++)c&&b.features[g].setInfoTemplate(c),this.resultLayer.add(b.features[g]);this.resultLayer.setRenderer(d);try{var e=
t.graphicsExtent(b.features);e&&(this.resultLayer.fullExtent=e.expand(1.4),this.map.setExtent(this.resultLayer.fullExtent))}catch(f){console.error(f)}},_addResultLayer:function(a){var b=new z(this.config,this.map);try{b.calculateLayerIndex(a,this.widgetUID).then(e.hitch(this,function(a){-1!==a?this.map.addLayer(this.resultLayer,a):this.map.addLayer(this.resultLayer)}))}catch(c){console.error(c.message),console.warn("Draw result feature set on the top of map"),this.map.addLayer(this.resultLayer)}},
_generatePopupContent:function(a){var b="";n.forEach(this.param.popup.fields&&0<this.param.popup.fields.length?this.param.popup.fields:a.fields,function(a){b+='\x3ctr valign\x3d"top"\x3e\x3ctd class\x3d"attr-name"\x3e'+a.alias+'\x3c/td\x3e\x3ctd class\x3d"attr-value"\x3e${'+a.name+"}\x3c/td\x3e\x3c/tr\x3e"});return'\x3cdiv class\x3d"geoprocessing-popup"\x3e\x3ctable class\x3d"geoprocessing-popup-table" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\x3ctbody\x3e'+b+"\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e"}})});