// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/html dijit/_WidgetBase dgrid/OnDemandGrid dgrid/Selection dgrid/extensions/ColumnHider dgrid/extensions/ColumnResizer dgrid/extensions/ColumnReorder dojo/Deferred dojo/Evented dojo/store/Memory esri/request esri/tasks/RelationshipQuery esri/lang dojo/_base/lang dojo/on dojo/_base/array jimu/dijit/LoadingIndicator jimu/CSVUtils ./utils".split(" "),function(p,f,s,t,u,v,w,x,q,y,r,z,A,l,e,B,k,C,D,m){return p([s,y],{baseClass:"jimu-widget-attributetable-relationship-table",
_defaultFeatureCount:2E3,_defaultBatchCount:25,_batchCount:0,_currentDef:null,_requestStatus:"initial",relationship:null,parentWidget:null,noGridHeight:0,footerHeight:25,loading:null,grid:null,footer:null,selectedRowsLabel:null,selectionRows:null,nls:null,_onlyShowSelected:!1,constructor:function(b){b=b||{};this.set("relationship",b.relationship||null);this.parentWidget=b.parentWidget||null;this.noGridHeight=b.noGridHeight||0;this.originalInfo=b.originalInfo},postCreate:function(){this.selectionRows=
[];this.loading=new C;this.loading.placeAt(this.domNode)},cancelThread:function(){"fulfilled"!==this._requestStatus&&this._currentDef&&(this._currentDef.cancel({canceledBySelf:!0}),this._requestStatus="canceled")},isCanceled:function(){return"canceled"===this._requestStatus},startQuery:function(b,c){var a=this.relationship;if(a&&!a.opened&&c&&0<c.length&&e.exists("originalInfo.layerObject.url",this)){this.loading.show();this._requestStatus="processing";if(!e.exists("relatedTableUrl",this)){var d=
this.originalInfo.layerObject.url.split("/");d[d.length-1]=this.relationship.relatedTableId;this.relatedTableUrl=d.join("/")}this._currentDef=d=z({url:this.relatedTableUrl,content:{f:"json"},hangleAs:"json",callbackParamName:"callback"});d.then(e.hitch(this,function(d){if(this.domNode){var g=this._getRelatedTableInfo();this._currentDef=g;g.then(e.hitch(this,function(g){if(g){var h=this.parentWidget._getLayerInfoByIdFromConfigJSON(g.id);g=m.getConfigInfoFromLayerInfo(g);h=e.exists("layer.fields",h)&&
h.layer.fields||e.exists("layer.fields",g)&&g.layer.fields;m.merge(d.fields,h,"name",function(a,d){e.mixin(a,d)})}var n=[];k.forEach(d.fields,function(a){(!l.isDefined(a)||!0===a.show||"esriFieldTypeOID"===a.type||l.isDefined(d.objectIdField)&&a.name===d.objectIdField)&&n.push(a.name)});h=new A;h.objectIds=c;h.outFields=n.length?n:["*"];h.relationshipId=a.id;h.returnGeometry=!1;(this._currentDef=b.queryRelatedFeatures(h,function(a){return a})).then(e.hitch(this,function(b){if(this.domNode){var c=
{displayFieldName:a.objectIdField,fields:d.fields,features:[],fieldAliases:null},e;for(e in b){var g=b[e];g.features&&0<g.features.length&&(c.features=c.features.concat(g.features))}0<c.features.length?(this.tableDefinition=d,this.createTable(d,c),this.emit("data-loaded")):(b=f.toDom("\x3cdiv\x3e"+this.nls.noRelatedRecords+"\x3c/div\x3e"),this._removeTable(),f.empty(this.domNode),f.place(b,this.domNode),f.place(this.loading.domNode,this.domNode));a.opened=!0;this.loading.hide()}}),e.hitch(this,function(a){console.error(a);
this._removeTable();f.empty(this.domNode);f.place(this.loading.domNode,this.domNode);this.loading.hide()}))}))}}),e.hitch(this,function(a){console.error(a);this.loading.hide()}))}else this.loading.hide()},getSelectedRows:function(){return this.selectionRows},zoomTo:function(){},toggleSelectedRecords:function(){this._onlyShowSelected?this.showAllSelectedRecords():this.showSelectedRecords();this._onlyShowSelected=!this._onlyShowSelected},showSelectedRecords:function(){var b=this.relationship.objectIdField;
this.grid._clickShowSelectedRecords=!0;var c=this._getSelectedIds();0<c.length&&this.grid&&this.grid.set("query",e.hitch(this,function(a){return"number"===typeof a&&-1<c.indexOf(a)||-1<c.indexOf(a[b])?!0:!1}))},showAllSelectedRecords:function(){this.grid.set("query",{});k.forEach(this.selectionRows,e.hitch(this,function(b){this.grid.select(b)}));this.setSelectedNumber()},clearSelection:function(){this.grid.clearSelection();this.selectionRows=[];this.grid.set("query",{});this.setSelectedNumber();this._onlyShowSelected=
!1;this.emit("clear-selection")},exportToCSV:function(b){if(this.relationship&&this.tableDefinition){var c=this.grid.__outFields,a=this.getSelectedRowsData(),d={};a&&0<a.length?d.datas=a:this.grid.store instanceof r&&(a=this.grid.store.data,d.datas=a);d.fromClient=!1;d.outFields=c;d.formatNumber=!1;d.formatDate=!0;d.formatCodedValue=!0;return D.exportCSVFromFeatureLayer(b,this.tableDefinition,d)}},toggleColumns:function(){this.grid&&this.grid._toggleColumnHiderMenu()},changeHeight:function(b){this.grid&&
0<=b-this.noGridHeight-this.footerHeight&&f.setStyle(this.grid.domNode,"height",b-this.noGridHeight-this.footerHeight+"px")},destroy:function(){this.parentWidget=this.configedInfo=this.layerInfo=null;this.grid&&this.grid.destroy();this.nls=this.map=null;this.relationship.opened=!1;this.relationship=null;this.inherited(arguments)},createTable:function(b,c){var a=k.map(c.features,e.hitch(this,function(a){return a.attributes})),d=m.generateMemoryStore(a,c.displayFieldName),E=m.generateColumnsFromFields(c.fields,
b.typeIdField,b.types);this.grid?(this.grid.set("store",d),this.grid.refresh()):(d={columns:E,store:d,keepScrollPosition:!0,pagingDelay:1E3},this.grid=new (p([t,u,v,w,x]))(d,f.create("div")),f.empty(this.domNode),f.place(this.grid.domNode,this.domNode),this.grid.startup(),this.grid.__pk=c.displayFieldName,this.grid.__outFields=c.fields,this.own(B(this.grid,".dgrid-row:click",e.hitch(this,this._onRowClick))));this.footer?f.empty(this.footer):this.footer=f.create("div",null,this.domNode);a=f.create("div",
{"class":"dgrid-status self-footer",innerHTML:a.length+"\x26nbsp;"+this.nls.features+"\x26nbsp;"},this.footer);this.selectedRowsLabel=f.create("div",{"class":"dgrid-status self-footer",innerHTML:"0\x26nbsp;"+this.nls.selected+"\x26nbsp;"},a,"after");a=f.getStyle(this.parentWidget.domNode,"height");this.changeHeight(a);this._requestStatus="fulfilled"},_getRelatedTableInfo:function(){var b=new q;if(this.relatedTableInfo)b.resolve(this.relatedTableInfo);else{var c=this.originalInfo.getRelatedTableInfoArray();
this._currentDef=c;c.then(e.hitch(this,function(a){(a=k.filter(a,e.hitch(this,function(a){a=a.getUrl();return l.isDefined(a)&&l.isDefined(this.relatedTableUrl)&&a.toLowerCase()===this.relatedTableUrl.toLowerCase()})))&&0<a.length?(this.relatedTableInfo=a[0],b.resolve(this.relatedTableInfo)):b.resolve(null)}),e.hitch(function(a){console.error(a);b.resolve(null)}))}return b},_removeTable:function(){this.grid&&this.grid.domNode&&(this.grid.destroy(),this.grid=null);this.footer&&(f.destroy(this.footer),
this.selectedRowsLabel=this.footer=null)},_getExportData:function(){if(this.relationship){var b=new q,c=this.grid.__outFields,a=this.relationship.objectIdField,d=this.getSelectedRowsData();d&&0<d.length?b.resolve({data:d,outFields:c,pk:a,types:null}):(d=this.grid.store,d instanceof r?(d=d.data,b.resolve({data:d,outFields:c,pk:a,types:null})):b.resolve({data:[],outFields:c,pk:a,types:null}));return b}},getSelectedRowsData:function(){if(!this.grid)return null;var b=this.relationship.objectIdField,c=
this.grid.store,a=c._entityData||c.data,c=this.getSelectedRows();return k.map(c,e.hitch(this,function(d){for(var c=0,e=a.length;c<e;c++)if(a[c]&&a[c][b]===d)return a[c];return{}}))||[]},setSelectedNumber:function(){if(this.selectedRowsLabel&&this.grid){var b=this.getSelectedRows();this.selectedRowsLabel.innerHTML="\x26nbsp;\x26nbsp;"+b.length+" "+this.nls.selected+"\x26nbsp;\x26nbsp;"}},_onRowClick:function(){this.selectionRows=this._getSelectedIds();this.setSelectedNumber();this.emit("row-click",
{table:this,selectedIds:e.clone(this.selectionRows)})},_getSelectedIds:function(){var b=[],c=this.grid.selection,a;for(a in c)c[a]&&(isFinite(a)?b.push(parseInt(a,10)):b.push(a));return b}})});