// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./FeatureLayerQueryStore jimu/utils".split(" "),function(f,h,q,m,p,b,v,w,r,s,x,n){function y(a){var c=[],b=[];h.forEach(a,function(e){var g=c.indexOf(e.name);0>g?c.push(e.name):(b.push(a[g]),b.push(e))});h.forEach(b,function(a){a.name=a.name+"-"+a.id})}b.readLayerInfosObj=function(a){return q.getInstance(a,a.itemInfo)};b.readLayerInfosFromMap=
function(a,c,b){var e=new m;q.getInstance(a,a.itemInfo).then(f.hitch(this,function(a){var d=[];c?a.traversalLayerInfosOfWebmap(function(a){d.push(a)}):a.traversal(function(a){d.push(a)});if(b){var l=[],f=a.getMapNotesLayerInfoArray();h.forEach(f,function(a){l.push(a.id);a.traversal(function(a){l.push(a.id)})});d=h.filter(d,function(a){return-1===l.indexOf(a.id)})}a=a.getTableInfoArray();d=d.concat(a);e.resolve(d)}),f.hitch(this,function(a){console.error(a);e.reject(a)}));return e.promise};b.generateColumnsFromFields=
function(a,c,t,e){var g={};h.forEach(a,f.hitch(b,function(d,l){var k="field"+l,u=!!d.domain,n="esriFieldTypeDate"===d.type,m=c&&d.name===c;g[k]={label:d.alias||d.name,className:k,hidden:!d.show&&s.isDefined(d.show),unhidable:!d.show&&s.isDefined(d.show)&&d._pk,field:d.name};g[k].sortable=!!e;if("esriFieldTypeString"===a[l].type)g[k].formatter=f.hitch(b,b.urlFormatter);else if("esriFieldTypeDate"===a[l].type)g[k].formatter=f.hitch(b,b.dateFormatter);else if("esriFieldTypeDouble"===a[l].type||"esriFieldTypeSingle"===
a[l].type||"esriFieldTypeInteger"===a[l].type||"esriFieldTypeSmallInteger"===a[l].type)g[k].formatter=f.hitch(b,b.numberFormatter);u?g[k].get=f.hitch(b,function(a,d){return this.getCodeValue(a.domain,d[a.name])},d):m?g[k].get=f.hitch(b,function(a,d,c){return this.getTypeName(c[a.name],d)},d,t):!u&&(!n&&!m)&&(g[k].get=f.hitch(b,function(a,d,c,e){var g=null;d&&c&&0<c.length&&(c=(c=h.filter(c,f.hitch(b,function(a){return a.name===e[d]})))&&c[0]||null)&&(c.domains&&c.domains[a.name]&&c.domains[a.name].codedValues)&&
(g=this.getCodeValue(c.domains[a.name],e[a.name]));return(a=null!==g?g:e[a.name])||isFinite(a)?a:""},d,c,t))}));return g};b.getTypeName=function(a,c){return n.fieldFormatter.getTypeName(a,c)};b.getCodeValue=function(a,c){return n.fieldFormatter.getCodedValue(a,c)};b.urlFormatter=function(a){return n.fieldFormatter.getFormattedUrl(a)};b.dateFormatter=function(a){return n.fieldFormatter.getFormattedDate(a)};b.numberFormatter=function(a){return n.fieldFormatter.getFormattedNumber(a)};b.readLayerObjectsFromMap=
function(a,c,b){var e=new m,g=[];this.readLayerInfosFromMap(a,c,b).then(f.hitch(this,function(a){h.forEach(a,f.hitch(this,function(a){g.push(a.getLayerObject())}));p(g).then(f.hitch(this,function(a){e.resolve(a)}),f.hitch(this,function(a){e.reject(a);console.error(a)}))}),f.hitch(this,function(a){e.reject(a)}));return e.promise};b.readSupportTableInfoFromLayerInfos=function(a){var c=new m,b=[];h.forEach(a,f.hitch(this,function(a){b.push(a.getSupportTableInfo())}));p(b).then(f.hitch(this,function(b){b=
f.clone(b);h.forEach(b,function(c,b){c.id=a[b].id});c.resolve(b)}),function(a){c.reject(a)});return c.promise};b.readConfigLayerInfosFromMap=function(a,c,b){var e=new m,g=[];this.readLayerInfosFromMap(a,c,b).then(f.hitch(this,function(a){var c=[];h.forEach(a,function(a){g.push(a.getSupportTableInfo())});p(g).then(f.hitch(this,function(b){h.forEach(b,f.hitch(this,function(b,e){b.isSupportedLayer&&(a[e].name=a[e].title,c.push(a[e]))}));y(c);e.resolve(c)}),f.hitch(this,function(a){e.reject(a)}))}),f.hitch(this,
function(a){e.reject(a)}));return e.promise};b.getConfigInfosFromLayerInfos=function(a){return h.map(a,function(a){return b.getConfigInfoFromLayerInfo(a)})};b.getConfigInfoFromLayerInfo=function(a){var c={};c.name=a.name||a.title;c.id=a.id;c.show=a.isShowInMap();c.layer={url:a.getUrl()};if((a=a.getPopupInfo())&&!a.description)c.layer.fields=h.map(a.fieldInfos,function(a){return{name:a.fieldName,alias:a.label,show:a.visible}});return c};b.generateCacheStore=function(a,c,b,e,g){a=new x({layer:a,objectIds:a._objectIds||
null,totalCount:c,batchCount:b,where:e||"1\x3d1",spatialFilter:g});c=new r;return new w(a,c,{})};b.generateMemoryStore=function(a,c){return new v(new r({data:a||[],idProperty:c}))};b.merge=function(a,c,b,e){for(var g=h.map(c,function(a){return a[b]}),d=0,f=a.length;d<f;d++){var k=g.indexOf(a[d][b]);-1<k&&e(a[d],c[k])}}});