// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./FeatureLayerQueryStore jimu/utils".split(" "),function(g,m,s,q,f,c,d,v,h,t,u,p){function r(b){var a=[],k=[];m.forEach(b,function(e){var n=a.indexOf(e.name);0>n?a.push(e.name):(k.push(b[n]),k.push(e))});m.forEach(k,function(a){a.name=a.name+"-"+a.id})}c.readLayerInfosObj=
function(b){return s.getInstance(b,b.itemInfo)};c.readLayerInfosFromMap=function(b,a,k){var e=new q;s.getInstance(b,b.itemInfo).then(g.hitch(this,function(b){var l=[];a?b.traversalLayerInfosOfWebmap(function(a){l.push(a)}):b.traversal(function(a){l.push(a)});if(k){var f=[],c=b.getMapNotesLayerInfoArray();m.forEach(c,function(a){f.push(a.id);a.traversal(function(a){f.push(a.id)})});l=m.filter(l,function(a){return-1===f.indexOf(a.id)})}b=b.getTableInfoArray();l=l.concat(b);e.resolve(l)}),g.hitch(this,
function(a){console.error(a);e.reject(a)}));return e.promise};c.generateColumnsFromFields=function(b,a,k,e){var n={};m.forEach(b,g.hitch(c,function(l,f){var d="field"+f,h=!!l.domain,p="esriFieldTypeDate"===l.type,v=a&&l.name===a;n[d]={label:l.alias||l.name,className:d,hidden:!l.show&&t.isDefined(l.show),unhidable:!l.show&&t.isDefined(l.show)&&l._pk,field:l.name};n[d].sortable=!!e;if("esriFieldTypeString"===b[f].type)n[d].formatter=g.hitch(c,c.urlFormatter);else if("esriFieldTypeDate"===b[f].type)n[d].formatter=
g.hitch(c,c.dateFormatter);else if("esriFieldTypeDouble"===b[f].type||"esriFieldTypeSingle"===b[f].type||"esriFieldTypeInteger"===b[f].type||"esriFieldTypeSmallInteger"===b[f].type)n[d].formatter=g.hitch(c,c.numberFormatter);h?n[d].get=g.hitch(c,function(a,e){return this.getCodeValue(a.domain,e[a.name])},l):v?n[d].get=g.hitch(c,function(a,e,b){return this.getTypeName(b[a.name],e)},l,k):!h&&(!p&&!v)&&(n[d].get=g.hitch(c,function(a,e,b,k){var n=null;e&&b&&0<b.length&&(b=(b=m.filter(b,g.hitch(c,function(a){return a.name===
k[e]})))&&b[0]||null)&&(b.domains&&b.domains[a.name]&&b.domains[a.name].codedValues)&&(n=this.getCodeValue(b.domains[a.name],k[a.name]));return(a=null!==n?n:k[a.name])||isFinite(a)?a:""},l,a,k))}));return n};c.getTypeName=function(b,a){return p.fieldFormatter.getTypeName(b,a)};c.getCodeValue=function(b,a){return p.fieldFormatter.getCodedValue(b,a)};c.urlFormatter=function(b){return p.fieldFormatter.getFormattedUrl(b)};c.dateFormatter=function(b){return p.fieldFormatter.getFormattedDate(b)};c.numberFormatter=
function(b){return p.fieldFormatter.getFormattedNumber(b)};c.readLayerObjectsFromMap=function(b,a,k){var e=new q,n=[];this.readLayerInfosFromMap(b,a,k).then(g.hitch(this,function(a){m.forEach(a,g.hitch(this,function(a){n.push(a.getLayerObject())}));f(n).then(g.hitch(this,function(a){e.resolve(a)}),g.hitch(this,function(a){e.reject(a);console.error(a)}))}),g.hitch(this,function(a){e.reject(a)}));return e.promise};c.readSupportTableInfoFromLayerInfos=function(b){var a=new q,k=[];m.forEach(b,g.hitch(this,
function(a){k.push(a.getSupportTableInfo())}));f(k).then(g.hitch(this,function(e){e=g.clone(e);m.forEach(e,function(a,e){a.id=b[e].id});a.resolve(e)}),function(b){a.reject(b)});return a.promise};c.readConfigLayerInfosFromMap=function(b,a,k){var e=new q,n=[];this.readLayerInfosFromMap(b,a,k).then(g.hitch(this,function(a){var b=[];m.forEach(a,function(a){n.push(a.getSupportTableInfo())});f(n).then(g.hitch(this,function(k){m.forEach(k,g.hitch(this,function(e,k){e.isSupportedLayer&&(a[k].name=a[k].title,
b.push(a[k]))}));r(b);e.resolve(b)}),g.hitch(this,function(a){e.reject(a)}))}),g.hitch(this,function(a){e.reject(a)}));return e.promise};c.getConfigInfosFromLayerInfos=function(b){return m.map(b,function(a){return c.getConfigInfoFromLayerInfo(a)})};c.getConfigInfoFromLayerInfo=function(b){var a={};a.name=b.name||b.title;a.id=b.id;a.show=b.isShowInMap();a.layer={url:b.getUrl()};if((b=b.getPopupInfo())&&!b.description)a.layer.fields=m.map(b.fieldInfos,function(a){return{name:a.fieldName,alias:a.label,
show:a.visible}});return a};c.generateCacheStore=function(b,a,k,e,n){b=new u({layer:b,objectIds:b._objectIds||null,totalCount:a,batchCount:k,where:e||"1\x3d1",spatialFilter:n});a=new h;return new v(b,a,{})};c.generateMemoryStore=function(b,a){return new d(new h({data:b||[],idProperty:a}))};c.merge=function(b,a,k,e){for(var n=m.map(a,function(a){return a[k]}),f=0,d=b.length;f<d;f++){var c=n.indexOf(b[f][k]);-1<c&&e(b[f],a[c])}}})},"dojo/store/Observable":function(){define(["../_base/kernel","../_base/lang",
"../when","../_base/array"],function(g,m,s,q){g=function(f){function c(d,c){var h=f[d];h&&(f[d]=function(b){var a;"put"===d&&(a=f.getIdentity(b));if(t)return h.apply(this,arguments);t=!0;try{var k=h.apply(this,arguments);s(k,function(e){c("object"==typeof e&&e||b,a)});return k}finally{t=!1}})}var d=[],g=0;f=m.delegate(f);f.notify=function(f,c){g++;for(var h=d.slice(),b=0,a=h.length;b<a;b++)h[b](f,c)};var h=f.query;f.query=function(c,t){t=t||{};var r=h.apply(this,arguments);if(r&&r.forEach){var b=
m.mixin({},t);delete b.start;delete b.count;var a=f.queryEngine&&f.queryEngine(c,b),k=g,e=[],n;r.observe=function(b,c){1==e.push(b)&&d.push(n=function(b,n){s(r,function(d){var h=d.length!=t.count,l,m;if(++k!=g)throw Error("Query is out of date, you must observe() the query prior to any data modifications");var s,u=-1,r=-1;if(void 0!==n){l=0;for(m=d.length;l<m;l++){var w=d[l];if(f.getIdentity(w)==n){s=w;u=l;(a||!b)&&d.splice(l,1);break}}}if(a){if(b&&(a.matches?a.matches(b):a([b]).length))l=-1<u?u:
d.length,d.splice(l,0,b),r=q.indexOf(a(d),b),d.splice(l,1),t.start&&0==r||!h&&r==d.length?r=-1:d.splice(r,0,b)}else b&&(void 0!==n?r=u:t.start||(r=f.defaultIndex||0,d.splice(r,0,b)));if((-1<u||-1<r)&&(c||!a||u!=r)){h=e.slice();for(l=0;d=h[l];l++)d(b||s,u,r)}})});var h={};h.remove=h.cancel=function(){var a=q.indexOf(e,b);-1<a&&(e.splice(a,1),e.length||d.splice(q.indexOf(d,n),1))};return h}}return r};var t;c("put",function(d,c){f.notify(d,c)});c("add",function(d){f.notify(d)});c("remove",function(d){f.notify(void 0,
d)});return f};m.setObject("dojo.store.Observable",g);return g})},"dojo/store/Cache":function(){define(["../_base/lang","../when"],function(g,m){var s=function(q,f,c){c=c||{};return g.delegate(q,{query:function(d,g){var h=q.query(d,g);h.forEach(function(d){(!c.isLoaded||c.isLoaded(d))&&f.put(d)});return h},queryEngine:q.queryEngine||f.queryEngine,get:function(d,c){return m(f.get(d),function(h){return h||m(q.get(d,c),function(c){c&&f.put(c,{id:d});return c})})},add:function(d,c){return m(q.add(d,c),
function(h){f.add(h&&"object"==typeof h?h:d,c);return h})},put:function(d,c){f.remove(c&&c.id||this.getIdentity(d));return m(q.put(d,c),function(h){f.put(h&&"object"==typeof h?h:d,c);return h})},remove:function(d,c){return m(q.remove(d,c),function(h){return f.remove(d,c)})},evict:function(d){return f.remove(d)}})};g.setObject("dojo.store.Cache",s);return s})},"widgets/AttributeTable/FeatureLayerQueryStore":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array esri/tasks/query esri/tasks/QueryTask ./FeatureLayerQueryResult".split(" "),
function(g,m,s,q,f,c){return g(null,{queryUrl:"",idProperty:"id",data:null,_entityData:null,constructor:function(d){g.safeMixin(this,d);this.data=[];this._entityData=[];this.layer=d.layer;this.objectIds=d.objectIds;this.where=d.where;this.orderByFields=d.orderByFields;this.totalCount=d.totalCount;this.batchCount=d.batchCount||25;this.idProperty=this.layer.objectIdField;this.spatialFilter=d.spatialFilter;this.layer&&this.layer.url&&(this.queryTask=new f(this.layer.url))},get:function(d){return this.data[d]},
getIdentity:function(d){return d[this.idProperty]},query:function(d,f){var h=new q,g=f&&f.start||0,u=this.batchCount,p=null;"function"===typeof d?p=d(this._entityData):"[object Array]"===Object.prototype.toString.call(d)&&(p=d);if(this.objectIds)p=p?p:this.objectIds,h.objectIds=p.length>=g+this.batchCount?p.slice(g,g+u):p.slice(g);else if(p&&0<p.length?h.objectIds=p.length>=g+this.batchCount?p.slice(g,g+u):p.slice(g):(h.start=g,h.num=u,h.where=this.where,h.geometry=this.spatialFilter,h.spatialRelationship=
q.SPATIAL_REL_INTERSECTS),(g=f.sort)&&0<g.length)g=s.map(g,function(b){return b.attribute+" "+(b.descending?"DESC":"ASC")}),h.orderByFields=g;h.returnGeometry=!1;h.outFields=["*"];var r=this.totalCount,g=null,g=!h.where;if(!(h.objectIds&&0<h.objectIds.length)&&g)return new c([]);g=this.queryTask?this.queryTask.execute(h):this.layer.queryFeatures(h);g.total=g.then(m.hitch(this,function(b){var a=0,k=this.layer.objectIdField;if(this.objectIds){if(!k)for(a=0;a<b.fields.length;a++)if("esriFieldTypeOID"===
b.fields[a].type){k=b.fields[a].name;break}for(var e={},a=0;a<b.features.length;a++)e[b.features[a].attributes[k]]=b.features[a];b.features=s.map(h.objectIds,function(a){return e[a]})}for(a=0;a<b.features.length;a++)b.features[a]&&(b.features[a]=b.features[a].attributes,this.data[b.features[a][k]]=b.features[a],this._entityData.push(b.features[a]));b=b.features;return r}),function(){console.log("FeatureLayerQueryStore queryFeatures failed.");return 0});return new c(g)}})})},"widgets/AttributeTable/FeatureLayerQueryResult":function(){define("esri/main dojo/_base/lang dojo/_base/kernel dojo/_base/Deferred dojo/DeferredList dojo/_base/array".split(" "),
function(g,m,s,q){var f=function(c){function d(d){c[d]||(c[d]=function(){var g=arguments;return q.when(c,function(c){Array.prototype.unshift.call(g,c.features||c);return f(s[d].apply(s,g))})})}if(!c)return c;c.then&&(c=m.delegate(c));c.total||(c.total=q.when(c,function(d){return g._isDefined(d.total)?d.total:d.length||0}));d("forEach");d("filter");d("map");d("some");d("every");return c};return f})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html",
"dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n  \x3c!-- \x3cdiv data-dojo-attach-point\x3d"tableEditInfosError" style\x3d"display:none"\x3e\x3c/div\x3e --\x3e\r\n  \x3cdiv class\x3d"table-options jimu-ellipsis"\x3e\r\n\t\t\x3cdiv data-dojo-attach-point\x3d"exportcsv" checked \r\n        data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n  \t\x3cdiv data-dojo-attach-point\x3d"expand" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.expand}"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:14px; width: 100%; height: 100%; position: relative;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; height: 550px;}.jimu-widget-attributetable-setting .table-options{margin-top: 10px;}.jimu-widget-attributetable-setting .jimu-checkbox{margin-right: 20px;}.jimu-widget-attributetable-setting .disable-checkbox{color: #e5e5e5;}",
"*now":function(g){g(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","cs","da","de","en","el","es","et","fi","fr","he","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/query jimu/dijit/Popup jimu/dijit/Message jimu/dijit/LoadingShelter ../utils".split(" "),function(g,m,s,q,f,c,d,v,h,t,u,p,r,b){return g([s,m],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,_allLayerFields:null,_layerInfos:null,_tableInfos:null,_delayedLayerInfos:null,_delayedLayerInfosAfterInit:null,
_unSpportQueryCampsite:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._tableInfos=[];this._delayedLayerInfos=[];this._delayedLayerInfosAfterInit=[];this._unSpportQueryCampsite={};this.displayFieldsTable=new q({fields:[{name:"show",title:this.nls.show,width:"auto",type:"checkbox","class":"show"},{name:"label",title:this.nls.label,width:"60%",type:"text"},{name:"url",title:"url",type:"text",hidden:!0},
{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",width:"20%",actions:["edit"],"class":"symbol"}],selectable:!0,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);c.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.shelter=new r({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();this.shelter.show();b.readLayerInfosObj(this.map).then(f.hitch(this,function(a){this.own(a.on("layerInfosChanged",
f.hitch(this,this.onLayerInfosChanged)));this.own(v(this.displayFieldsTable,"actions-edit",f.hitch(this,this.editFieldsClick)));this.own(v(this.displayFieldsTable,"row-click",f.hitch(this,this._verifiedOnShowClick)));this.setConfig(this.config)}))},editFieldsClick:function(a){var b=t(".action-item-parent",a);if(b&&b.length)if(b=this.displayFieldsTable.getRowData(a),b.show){var e=parseInt(b.index,10);this.shelter.show();this._getLayerFields(e).then(f.hitch(this,function(b){this.openFieldsDialog(a,
b,e)}),f.hitch(this,function(a){console.error(a)})).always(f.hitch(this,function(){this.shelter.hide()}))}else var d=new p({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:f.hitch(this,function(){d.close()})}]})},_verifiedOnShowClick:function(a){var b=this.displayFieldsTable.getRowData(a),e=parseInt(b.index,10),d=null,d=this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?this.config.layerInfos[e]:this._layerInfos[e],e=-1<this._unSpportQueryCampsite.layerNames.indexOf(d.name||
d.title);b.show&&e&&(new p({message:this.nls.unsupportQueryWarning}),b.show=!1,this.displayFieldsTable.editRow(a,b))},_getLayerFields:function(a){return this._layerInfos[a].getLayerObject().then(f.hitch(this,function(c){var e=this._allLayerFields[a];c=d.map(c.fields,function(a){return{name:a.name,alias:a.alias,show:!0}});b.merge(c,e,"name",function(a,b){f.mixin(a,b)});return c}))},openFieldsDialog:function(a,b,e){var c=this._createFieldsTable(b,e);this.currentFieldTable=c;this.own(v(c,"row-click",
f.hitch(this,function(a){var b=c.getData();if(!d.some(b,f.hitch(this,function(a){return a.show}))&&(new p({message:this.nls.fieldCheckWarning}),b=c.getRowData(a)))b.show=!0,c.editRow(a,b)})));var g=new u({titleLabel:this.nls.configureLayerFields,width:640,maxHeight:600,autoHeight:!0,content:c,buttons:[{label:this.nls.ok,onClick:f.hitch(this,function(){this._allLayerFields[e]=c.getData();g.close();g=null})},{label:this.nls.cancel,onClick:f.hitch(this,function(){g.close();g=null})}],onClose:function(){g=
null}});c.startup()},_createFieldsTable:function(a){for(var b=new q({fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show"},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!0,autoHeight:!1,style:{height:"300px",maxHeight:"300px"}}),e=0;e<a.length;e++)a[e].show=void 0===a[e].show?!0:!!a[e].show,
b.addRow(a[e]);return b},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this._processTableData().then(f.hitch(this,function(a){this._init(a);this.shelter.hide()}),f.hitch(this,function(a){new p({message:a.message||a})}))},onLayerInfosChanged:function(a,b,e){"added"!==b||(!e||!a)||e.getSupportTableInfo().then(f.hitch(this,function(a){a.isSupportedLayer&&(this._layerInfos&&0===this._layerInfos.length?this._delayedLayerInfos.push(e):this._layerInfos&&(0<this._layerInfos.length&&
!this._getLayerInfoById(e.id))&&(this._delayedLayerInfosAfterInit.push(e),this._processDelayedLayerInfosAfterInit(this._delayedLayerInfosAfterInit)))}))},_processDelayedLayerInfosAfterInit:function(a){for(var d=this._layerInfos.length,e=0;e<a.length;e++){var c=b.getConfigInfoFromLayerInfo(a[e]);this.displayFieldsTable.addRow({label:c.name||c.title,url:c.layer.url,index:""+(d+e),show:c.show});this._allLayerFields.push(c.layer.fields);this._layerInfos.push(a[e])}},_processDelayedLayerInfos:function(){0<
this._delayedLayerInfos.length&&(d.forEach(this._delayedLayerInfos,f.hitch(this,function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=new h;b.readConfigLayerInfosFromMap(this.map,!0,!0).then(f.hitch(this,function(c){this._layerInfos=c;this._processDelayedLayerInfos();b.readSupportTableInfoFromLayerInfos(this._layerInfos).then(f.hitch(this,function(e){this._tableInfos=e;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?
(e=b.getConfigInfosFromLayerInfos(this._layerInfos),b.merge(e,this.config.layerInfos,"id",f.hitch(this,function(a,e){a.name=e.name;a.show=e.show;a.layer.url=e.layer.url;f.exists("layer.fields.length",a)&&f.exists("layer.fields.length",e)?b.merge(a.layer.fields,e.layer.fields,"name",function(a,b){f.mixin(a,b)}):a.layer.fields=e.layer.fields})),this.config.layerInfos=e,this._unSpportQueryCampsite.fromConfig=!0,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this.config.layerInfos),
a.resolve(e)):(this._unSpportQueryCampsite.fromConfig=!1,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this._layerInfos),a.resolve(b.getConfigInfosFromLayerInfos(c)))}),function(b){console.error(b);a.reject(b)})}),f.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_getUnsupportQueryLayerNames:function(a){var b=[];d.forEach(a,f.hitch(this,function(a){var c=this._getSupportTableInfoById(a.id);c&&!c.isSupportQuery&&b.push(a.name||a.title)}));return b},_init:function(a){for(var b=
[],e=0;e<a.length;e++){var d=a[e].show&&this._getSupportTableInfoById(a[e].id).isSupportQuery;this.displayFieldsTable.addRow({label:a[e].name||a[e].title,url:a[e].layer.url,index:""+e,show:d});this._allLayerFields.push(a[e].layer.fields);this._unSpportQueryCampsite.fromConfig&&(d=(d=this._unSpportQueryCampsite.layerNames)&&-1<d.indexOf(a[e].name||a[e].title),a[e].show&&d&&b.push(a[e].name||a[e].title))}this._unSpportQueryCampsite.fromConfig&&0<b.length&&new p({message:this.nls.unsupportQueryLayers+
"\x3cbr\x3e\x3cbr\x3e"+b.toString()});this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check();this.config.initiallyExpand?this.expand.check():this.expand.uncheck();this._canUseOpenAtStart()&&(this.openAtStart?this.expand.check():this.expand.uncheck(),this.expand.status=!1,c.addClass(this.expand.domNode,"disable-checkbox"))},_canUseOpenAtStart:function(){return this.closeable||!this.isOnScreen},_getLayerInfoById:function(a){for(var b=0,c=this._layerInfos.length;b<c;b++)if(this._layerInfos[b].id===
a)return this._layerInfos[b]},_getSupportTableInfoById:function(a){for(var b=0,c=this._tableInfos.length;b<c;b++)if(this._tableInfos[b].id===a)return this._tableInfos[b]},getConfig:function(){var a=this.displayFieldsTable.getData(),b=[],c=a.length;if(this.config&&this.config.layerInfos&&0<this.config.layerInfos.length)d.forEach(a,f.hitch(this,function(c,d){var e=this.config.layerInfos[d],f={};f.name=e.name||e.title;f.id=e.id;f.layer={};f.layer.url=a[d].url;f.layer.fields=this._allLayerFields[d];f.show=
a[d].show;b.push(f)}));else for(var g=0;g<c;g++){var h={};h.name=this._layerInfos[g].name||this._layerInfos[g].title;h.id=this._layerInfos[g].id;h.layer={};h.layer.url=a[g].url;h.layer.fields=this._allLayerFields[g];h.show=a[g].show;b.push(h)}this.config.layerInfos=b;this.config.hideExportButton=!this.exportcsv.getValue();this._canUseOpenAtStart()||(this.config.initiallyExpand=this.expand.getValue());return this.config}})});